
export const GET_BLOG_POSTS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/blogs`,
    REQUEST: 'REQUEST_GET_BLOG_POSTS',
    RECEIVED: 'RECEIVED_GET_BLOG_POSTS',
    RECEIVED_ERROR: 'RECEIVED_GET_BLOG_POSTS_ERROR',
});

export const GET_EACH_POST_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/blogs/`,
    REQUEST: 'REQUEST_GET_EACH_POST',
    RECEIVED: 'RECEIVED_GET_EACH_POST',
    RECEIVED_ERROR: 'RECEIVED_GET_EACH_POST_ERROR',
});

// export const GET_CAT_ID_CONSTANTS = ({
//     URL: `${process.env.APPLICATION_BFF_URL}/blogs/categories/`,
//     REQUEST: 'REQUEST_GET_CAT_ID',
//     RECEIVED: 'RECEIVED_GET_CAT_ID',
//     RECEIVED_ERROR: 'RECEIVED_GET_CAT_ID_ERROR',
// });

export const GET_EACH_BLOG_COMMENTS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/blogs/comments/`,
    REQUEST: 'REQUEST_BLOG_COMMENTS',
    RECEIVED: 'RECEIVED_BLOG_COMMENTS',
    RECEIVED_ERROR: 'RECEIVED_BLOG_COMMENTS_ERROR',
});

export const POST_BLOG_COMMENT_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/blogs/comment/`,
    REQUEST: 'REQUEST_POST_BLOG_COMMENT',
    RECEIVED: 'RECEIVED_POST_BLOG_COMMENT',
    RECEIVED_ERROR: 'RECEIVED_POST_BLOG_COMMENT_ERROR',
});
export const GET_BLOG_CATEGORIES_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/blogs/categories`,
    REQUEST: 'REQUEST_GET_BLOG_CATEGORIES',
    RECEIVED: 'RECEIVED_GET_BLOG_CATEGORIES',
    RECEIVED_ERROR: 'RECEIVED_GET_BLOG_CATEGORIES_ERROR',
});

export const GET_BLOG_COMMENTS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/blogs/comments`,
    REQUEST: 'REQUEST_GET_BLOG_COMMENTS',
    RECEIVED: 'RECEIVED_GET_BLOG_COMMENTS',
    RECEIVED_ERROR: 'RECEIVED_GET_BLOG_COMMENTS_ERROR',
});

// export const GET_TAGS_OF_POST_CONSTANTS = ({
//     URL: `${process.env.APPLICATION_BFF_URL}/blogs/tags/`,
//     REQUEST: 'REQUEST_GET_TAGS_OF_POST_CONSTANTS',
//     RECEIVED: 'RECEIVED_GET_TAGS_OF_POST_CONSTANTS',
//     RECEIVED_ERROR: 'RECEIVED_GET_TAGS_OF_POST_CONSTANTS',
// });

export const GET_INSTA_FEEDS_CONSTANTS = ({
    // URL: 'https://api.instagram.com/v1/users/self/media/recent/?access_token=2009620337.1677ed0.342687bd373340f9b230c794796d5030&count=20',
    URL: `${process.env.APPLICATION_BFF_URL}/blogs/insta/feed`,
    REQUEST: 'REQUEST_GET_INSTA_FEEDS_CONSTANTS',
    RECEIVED: 'RECEIVED_GET_INSTA_FEEDS_CONSTANTS',
    RECEIVED_ERROR: 'RECEIVED_GET_INSTA_FEEDS_CONSTANTS_ERROR',
});
