// Show Get Cart Constants
export const GET_CART_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/cart-list`;
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_RECEIVED = "GET_CART_RECEIVED";
export const GET_CART_ERROR = "GET_CART_ERROR";

// Show Filter Constants
export const FILTER_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/mageapi/filters/`;
export const REQUEST_FILTER = "REQUEST_FILTER";
export const RECEIVED_FILTER = "RECEIVED_FILTER";
export const RECEIVED_FILTER_ERROR = "RECEIVED_FILTER_ERROR";

// Show Quote Constants
export const QUOTE_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/carts/mine`;
export const REQUEST_QUOTE = "REQUEST_QUOTE";
export const RECEIVED_QUOTE = "RECEIVED_QUOTE";
export const RECEIVED_QUOTE_ERROR = "RECEIVED_QUOTE_ERROR";
// Show  Constants
export const CART_ITEMS_BY_CUSTOMER = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/carts/mine`;
export const REQUEST_CART_ITEMS_BY_CUSTOMER = "REQUEST_CART_ITEMS_BY_CUSTOMER";
export const RECEIVED_CART_ITEMS_BY_CUSTOMER =
  "RECEIVED_CART_ITEMS_BY_CUSTOMER";
export const RECEIVED_CART_ITEMS_BY_CUSTOMER_ERROR =
  "RECEIVED_CART_ITEMS_BY_CUSTOMER_ERROR";
// Show Cart Constants
export const FIRST_CART_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/carts/mine`;
export const REQUEST_FIRST_CART_SEARCH = "REQUEST_FIRST_CART_SEARCH";
export const RECEIVED_FIRST_CART_SEARCH = "RECEIVED_FIRST_CART_SEARCH";
export const RECEIVED_FIRST_CART_SEARCH_ERROR =
  "RECEIVED_FIRST_CART_SEARCH_ERROR";

export const ADD_TO_CART_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/add-to-cart`;
export const REQUEST_ADD_TO_CART = "REQUEST_ADD_TO_CART";
export const RECEIVED_ADD_TO_CART = "RECEIVED_ADD_TO_CART";
export const RECEIVED_ADD_TO_CART_ERROR = "RECEIVED_ADD_TO_CART_ERROR";

// Apply Discount Coupon Constants
export const DISCOUNT_COUPON_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/cart/coupon/`;
export const REQUEST_DISCOUNT_COUPON_SEARCH = "REQUEST_DISCOUNT_COUPON_SEARCH";
export const RECEIVED_DISCOUNT_COUPON_SEARCH =
  "RECEIVED_DISCOUNT_COUPON_SEARCH";
export const RECEIVED_DISCOUNT_COUPON_SEARCH_ERROR =
  "RECEIVED_DISCOUNT_COUPON_SEARCH_ERROR";

// Cancel Discount Coupon Constants
export const CANCEL_DISCOUNT_COUPON_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/cart/coupon`;
export const REQUEST_CANCEL_DISCOUNT_COUPON_SEARCH =
  "REQUEST_CANCEL_DISCOUNT_COUPON_SEARCH";
export const RECEIVED_CANCEL_DISCOUNT_COUPON_SEARCH =
  "RECEIVED_CANCEL_DISCOUNT_COUPON_SEARCH";
export const RECEIVED_CANCEL_DISCOUNT_COUPON_SEARCH_ERROR =
  "RECEIVED_CANCEL_DISCOUNT_COUPON_SEARCH_ERROR";

// Remove From Cart Constants
export const REMOVE_FROM_CART_URL_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/delete-cart-item/`,
  REQUEST: "REQUEST_REMOVE_FROM_CART",
  RECEIVED: "RECEIVED_REMOVE_FROM_CART",
  RECEIVED_ERROR: "RECEIVED_REMOVE_FROM_CART_ERROR",
};

// Update Cart Constants
export const UPDATE_CART_URL_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/update-cart/`,
  REQUEST: "REQUEST_UPDATE_CART",
  RECEIVED: "RECEIVED_UPDATE_CART",
  RECEIVED_ERROR: "RECEIVED_UPDATE_CART_ERROR",
};

// Move to WishList Constants
export const MOVE_TO_WISHLIST_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/wishlist`,
  REQUEST: "REQUEST_MOVE_TO_WISHLIST",
  RECEIVED: "RECEIVED_MOVE_TO_WISHLIST",
  RECEIVED_ERROR: "RECEIVED_MOVE_TO_WISHLIST_ERROR",
};

// Remove Expired Products Constants
export const REMOVE_EXPIRED_PRODUCTS_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/expired`,
  REQUEST: "REQUEST_REMOVE_EXPIRED_PRODUCTS_DATA",
  RECEIVED: "RECEIVED_REMOVE_EXPIRED_PRODUCTS_DATA",
  RECEIVED_ERROR: "RECEIVED_REMOVE_EXPIRED_PRODUCTS_ERROR",
};

export const CLEAR_CART_DATA = "CLEAR_CART_DATA";

// cart Type Constants
export const SET_CART_TYPE = "SET_CART_TYPE";

export const FLUSH_CART_VIEW_DATA = "FLUSH_CART_VIEW_DATA";

// Bulk Add to cart Constants
export const BULK_ADD_TO_CART_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/cart/bulk`,
  REQUEST: "REQUEST_BULK_ADD_TO_CART",
  RECEIVED: "RECEIVED_BULK_ADD_TO_CART",
  RECEIVED_ERROR: "RECEIVED_BULK_ADD_TO_CART_ERROR",
};

// Clear Cart
export const CLEAR_CART_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/cart/details`,
  REQUEST: "REQUEST_CLEAR_CART_DATA",
  RECEIVED: "RECEIVED_CLEAR_CART_DATA",
  RECEIVED_ERROR: "RECEIVED_CLEAR_CART_DATA_ERROR",
};

// Set Billing Address And Shipping Adrress
export const BILL_SHIP_ADD_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/carts/`;
export const REQUEST_BILL_SHIP_ADD = "REQUEST_BILL_SHIP_ADD";
export const RECEIVED_BILL_SHIP_ADD = "RECEIVED_BILL_SHIP_ADD";
export const RECEIVED_BILL_SHIP_ADD_ERROR = "RECEIVED_BILL_SHIP_ADD_ERROR";

export const RECEIVED_CART_DATA = "RECEIVED_CART_DATA";

export const SETTING_BILLING_AND_SHIPPING = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/carts/`,
  REQUEST: "REQUEST_SETTING_BILLING_AND_SHIPPING",
  RECEIVED: "RECEIVED_SETTING_BILLING_AND_SHIPPING",
  RECEIVED_ERROR: "RECEIVED_SETTING_BILLING_AND_SHIPPING_ERROR",
};

export const GUEST_ADD_TO_CART_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/guest-add-to-cart`;
export const GUEST_REQUEST_ADD_TO_CART = "GUEST_REQUEST_ADD_TO_CART";
export const GUEST_RECEIVED_ADD_TO_CART = "GUEST_RECEIVED_ADD_TO_CART";
export const GUEST_RECEIVED_ADD_TO_CART_ERROR =
  "GUEST_RECEIVED_ADD_TO_CART_ERROR";

export const GUEST_EDIT_TO_CART_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/guest-update-cart/`;
export const GUEST_REQUEST_EDIT_TO_CART = "GUEST_REQUEST_EDIT_TO_CART";
export const GUEST_RECEIVED_EDIT_TO_CART = "GUEST_RECEIVED_EDIT_TO_CART";
export const GUEST_RECEIVED_EDIT_TO_CART_ERROR =
  "GUEST_RECEIVED_EDIT_TO_CART_ERROR";

export const GUEST_DELETE_TO_CART_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/guest-delete-cart-item/`;
export const GUEST_REQUEST_DELETE_TO_CART = "GUEST_REQUEST_DELETE_TO_CART";
export const GUEST_RECEIVED_DELETE_TO_CART = "GUEST_RECEIVED_DELETE_TO_CART";
export const GUEST_RECEIVED_DELETE_TO_CART_ERROR =
  "GUEST_RECEIVED_DELETE_TO_CART_ERROR";

export const GUEST_CART_LIST_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/guest-cart-list/`;
export const GUEST_REQUEST_CART_LIST_CART = "GUEST_REQUEST_CART_LIST_CART";
export const GUEST_RECEIVED_CART_LIST_CART = "GUEST_RECEIVED_CART_LIST_CART";
export const GUEST_RECEIVED_CART_LIST_ERROR = "GUEST_RECEIVED_CART_LIST_ERROR";

export const GUEST_CONVERT_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/guest-convert-cart/`;
export const GUEST_REQUEST_CONVERT_CART = "GUEST_REQUEST_CONVERT_CART";
export const GUEST_RECEIVED_CONVERT_CART = "GUEST_RECEIVED_CONVERT_CART";
export const GUEST_RECEIVED_CONVERT_ERROR = "GUEST_RECEIVED_CONVERT_ERROR";

export const REMOVE_CART_VALUE_DATA = "REMOVE_CART_VALUE_DATA";

export const GIFT_MESSAGE = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/add-gift-message`;
export const REQUEST_GIFT_MESSAGE = "REQUEST_GIFT_MESSAGE";
export const RECEIVED_GIFT_MESSAGE = "RECEIVED_GIFT_MESSAGE";
export const RECEIVED_GIFT_MESSAGE_ERROR = "RECEIVED_GIFT_MESSAGE_ERROR";
