export const CONTACT_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/user/contact`,
    REQUEST: 'REQUEST_SUBMIT_CONTACT_DATA',
    RECEIVED: 'RECEIVED_SUBMIT_CONTACT_DATA',
    RECEIVED_ERROR: 'RECEIVED_SUBMIT_CONTACT_ERROR',
});