export const LOGIN_URL = `${process.env.APPLICATION_BFF_URL}/user/login`;

export const REQUEST_LOGIN_DATA = "REQUEST_LOGIN_DATA";
export const RECEIVED_LOGIN_DATA = "RECEIVED_LOGIN_DATA";
export const RECEIVED_LOGIN_ERROR = "RECEIVED_LOGIN_ERROR";

export const FORGOT_PASSWORD_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/customers/password`;

export const REQUEST_FORGOT_PASSWORD_DATA = "REQUEST_FORGOT_PASSWORD_DATA";
export const RECEIVED_FORGOT_PASSWORD_DATA = "RECEIVED_FORGOT_PASSWORD_DATA";
export const RECEIVED_FORGOT_PASSWORD_ERROR = "RECEIVED_FORGOT_PASSWORD_ERROR";

export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";
export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL";

export const REQUEST_LOGOUT = "REQUEST_LOGOUT";

export const CLEAR_SALES_REP_FLAG = "CLEAR_SALES_REP_FLAG";

export const SET_ZIPCODE = "SET_ZIPCODE";

export const SET_CATNAME = "SET_CATNAME";
export const SET_CATDESC = "SET_CATDESC";

export const SET_STORE_ID = "SET_STORE_ID";

export const SET_CART_ID = "SET_CART_ID";

export const FLUSH_CART_DATA = "FLUSH_CART_DATA";

export const UPDATE_CART = "UPDATE_CART";

export const RESET_FORGOT_PASSWORD_DATA = "RESET_FORGOT_PASSWORD_DATA";

export const NEWSLETTER_SUBSCRIPTION_DATA = "NEWSLETTER_SUBSCRIPTION_DATA";
/* for getting profile data */

export const PROFILE_DATA_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/info/account`,
  REQUEST: "REQUEST_PROFILE_DATA",
  RECEIVED: "RECEIVED_PROFILE_DATA",
  RECEIVED_ERROR: "REQUEST_PROFILE_DATA_ERROR",
};

export const CATEGORIES_LIST_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/product/categories/list`,
  REQUEST: "REQUEST_CATEGORIES_LIST",
  RECEIVED: "RECEIVED_CATEGORIES_LIST",
  RECEIVED_ERROR: "REQUEST_CATEGORIES_LIST_ERROR",
};

export const NEWSLETTER_SUBSCRIPTION_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/newsLetter/subscription`,
  REQUEST: "REQUEST_NEWSLETTER_SUBSCRIPTION",
  RECEIVED: "RECEIVED_NEWSLETTER_SUBSCRIPTION",
  RECEIVED_ERROR: "REQUEST_NEWSLETTER_SUBSCRIPTION_ERROR",
};

export const USER_LOGOUT_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/user/logout`,
  REQUEST: "REQUEST_USER_LOGOUT",
  RECEIVED: "RECEIVED_USER_LOGOUT",
  RECEIVED_ERROR: "REQUEST_USER_LOGOUT_ERROR",
};

export const UPDATE_PRIME_ID = "UPDATE_PRIME_ID";

export const ARTIST_EMAIL_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/artist/email/`,
  REQUEST: "REQUEST_ARTIST_EMAIL_CONSTANTS",
  RECEIVED: "RECEIVED_ARTIST_EMAIL_CONSTANTS",
  RECEIVED_ERROR: "REQUEST_ARTIST_EMAIL_CONSTANTS_ERROR",
};

export const HOME_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/V1/home/store_id/11`,
  REQUEST: "REQUEST_HOME_CONSTANTS",
  RECEIVED: "RECEIVED_HOME_CONSTANTS",
  RECEIVED_ERROR: "REQUEST_HOME_CONSTANTS_ERROR",
};

export const NEW_HOME_CONSTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/V1/home/store_id/11`,
  REQUEST: "REQUEST_NEW_HOME_CONSTANTS",
  RECEIVED: "RECEIVED_NEW_HOME_CONSTANTS",
  RECEIVED_ERROR: "REQUEST_NEW_HOME_CONSTANTS_ERROR",
};

export const TOKEN_CONTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/integration/customer/token`,
  REQUEST: "REQUEST_TOKEN_CONSTANTS",
  RECEIVED: "RECEIVED_TOKEN_CONSTANTS",
  RECEIVED_ERROR: "REQUEST_TOKEN_CONSTANTS_ERROR",
};

export const CUSTOMER_DETAILS_CONTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/customers/me`,
  REQUEST: "REQUEST_CUSTOMER_DETAILS_CONSTANTS",
  RECEIVED: "RECEIVED_CUSTOMER_DETAILS_CONSTANTS",
  RECEIVED_ERROR: "REQUEST_CUSTOMER_DETAILS_CONSTANTS_ERROR",
};
export const CUSTOMER_REGISTER_CONTANTS = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/customers`,
  REQUEST: "REQUEST_REGISTER_CONSTANTS",
  RECEIVED: "RECEIVED_REGISTER_CONSTANTS",
  RECEIVED_ERROR: "REQUEST_REGISTER_CONSTANTS_ERROR",
};

export const CUSTOMER_ZIPCODE = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/zipcodeByIp?ip=`,
  REQUEST: "REQUEST_CUSTOMER_ZIPCODE",
  RECEIVED: "RECEIVED_CUSTOMER_ZIPCODE",
  RECEIVED_ERROR: "REQUEST_CUSTOMER_ZIPCODE_ERROR",
};

export const UPDATE_CUSTOMER_DETAIL = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/customers/`,
  REQUEST: "REQUEST_UPDATE_CUSTOMER_DETAIL",
  RECEIVED: "RECEIVED_UPDATE_CUSTOMER_DETAIL",
  RECEIVED_ERROR: "REQUEST_UPDATE_CUSTOMER_DETAIL",
};

export const UPDATE_RESET_CUSTOMER_PASSWORD = {
  URL: `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/customers/resetPassword`,
  REQUEST: "REQUEST_UPDATE_RESET_CUSTOMER_PASSWORD",
  RECEIVED: "RECEIVED_UPDATE_RESET_CUSTOMER_PASSWORD",
  RECEIVED_ERROR: "REQUEST_UPDATE_RESET_CUSTOMER_PASSWORD_ERROR",
};
