export const MYFAVOURITE_DATA_URL = `${process.env.APPLICATION_BFF_URL}/info/favourite/list`;
export const REQUEST_MYFAVOURITE_INFO = 'REQUEST_MYFAVOURITE_INFO';
export const RECEIVE_MYFAVOURITE_INFO = 'RECEIVE_MYFAVOURITE_INFO';
export const RECEIVED_MYFAVOURITE_INFO_ERROR = 'RECEIVED_MYFAVOURITE_INFO_ERROR';


export const MYFAVOURITE_REMOVE_URL = `${process.env.APPLICATION_BFF_URL}/info/favourite`;
export const REQUEST_REMOVE_FROM_MYFAVOURITE = 'REQUEST_REMOVE_FROM_MYFAVOURITE';
export const RECEIVE_UPDATED_MYFAVOURITE_INFO = 'RECEIVE_UPDATED_MYFAVOURITE_INFO';
export const RECEIVED_UPDATED_MYFAVOURITE_INFO_ERROR = 'RECEIVED_UPDATED_MYFAVOURITE_INFO_ERROR';


export const ADD_TO_FAVORITES_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/favourite`,
    REQUEST: 'REQUEST_ADD_TO_FAVORITES',
    RECEIVED: 'RECEIVED_ADD_TO_FAVORITES',
    RECEIVED_ERROR: 'RECEIVED_ADD_TO_FAVORITES_ERROR',
});



export const CLEAR_MYFAVOURITE_DATA = 'CLEAR_MYFAVOURITE_DATA';

