export const PAST_PURCHASE_URL = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/pastpurchases`,
    REQUEST: 'REQUEST_PAST_PURCHASE_DATA',
    RECEIVED: 'RECEIVED_PAST_PURCHASE_DATA',
    RECEIVED_ERROR: 'RECEIVED_PAST_PURCHASE_ERROR',
});