export const PLACE_ORDER_URL = `${process.env.APPLICATION_BFF_URL}/order/add`;
export const REQUEST_PLACE_ORDER_SEARCH = 'REQUEST_PLACE_ORDER_SEARCH';
export const RECEIVED_PLACE_ORDER_SEARCH = 'RECEIVED_PLACE_ORDER_SEARCH';
export const RECEIVED_PLACE_ORDER_SEARCH_ERROR = 'RECEIVED_PLACE_ORDER_SEARCH_ERROR';

export const REDIRECTION_TO_FIRSTDATA_URL = `${process.env.APPLICATION_BFF_URL}/payment`;
export const REQUEST_FIRSTDATA_SEARCH = 'REQUEST_FIRSTDATA_SEARCH';
export const RECEIVED_FIRSTDATA_SEARCH = 'RECEIVED_FIRSTDATA_SEARCH';
export const RECEIVED_FIRSTDATA_SEARCH_ERROR = 'RECEIVED_FIRSTDATA_SEARCH_ERROR';

export const CLEAR_PLACE_ORDER_DATA = 'CLEAR_PLACE_ORDER_DATA';

export const SET_FIRST_DATA_REDIRECTION = 'SET_FIRST_DATA_REDIRECTION';

export const PAYMENT_METHOD_INFO_URL = `${process.env.APPLICATION_BFF_URL}/info/payment`;
export const REQUEST_PAYMENT_METHOD_INFO_SEARCH = 'REQUEST_PAYMENT_METHOD_INFO_SEARCH';
export const RECEIVED_PAYMENT_METHOD_INFO_SEARCH = 'RECEIVED_PAYMENT_METHOD_INFO_SEARCH';
export const RECEIVED_PAYMENT_METHOD_INFO_SEARCH_ERROR = 'RECEIVED_PAYMENT_METHOD_INFO_SEARCH_ERROR';

export const SUBSCRIPTION_HELPER_URL = `${process.env.APPLICATION_BFF_URL}/cart/subscriptionHelper`;
export const REQUEST_SUBSCRIPTION_HELPER = 'REQUEST_SUBSCRIPTION_HELPER';
export const RECEIVED_SUBSCRIPTION_HELPER = 'RECEIVED_SUBSCRIPTION_HELPER';
export const RECEIVED_SUBSCRIPTION_HELPER_ERROR = 'RECEIVED_SUBSCRIPTION_HELPER_ERROR';

export const ADD_FIRST_DATA_CREDIT_CARD_CONSTANTS = ({
    FIRST_DATA_URL: `${process.env.APPLICATION_BFF_URL}/payment/firstdata`,
    AUTHORIZE_NET_URL: `${process.env.APPLICATION_BFF_URL}/payment/authorizeNet`,
    BRAINTREE_URL: `${process.env.APPLICATION_BFF_URL}/payment/braintree/authorize`,
    // URL: 'http://localhost:2001/admin-bff/payment/firstdata',
    REQUEST: 'REQUEST_ADD_FIRST_DATA_CREDIT_CARD',
    RECEIVED: 'RECEIVED_ADD_FIRST_DATA_CREDIT_CARD',
    RECEIVED_ERROR: 'RECEIVED_ADD_FIRST_DATA_CREDIT_CARD_ERROR',
});

export const ADD_PAYPAL_CREDIT_CARD_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/payment/paypal`,
    REQUEST: 'REQUEST_ADD_PAYPAL_CREDIT_CARD',
    RECEIVED: 'RECEIVED_ADD_PAYPAL_CREDIT_CARD',
    RECEIVED_ERROR: 'RECEIVED_ADD_PAYPAL_CREDIT_CARD_ERROR',
});

export const GET_SAVED_CARD_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/payment/savedcard`,
    REQUEST: 'REQUEST_GET_SAVED_CARD_DETAILS',
    RECEIVED: 'RECEIVED_GET_SAVED_CARD_DETAILS',
    RECEIVED_ERROR: 'RECEIVED_GET_SAVED_CARD_DETAILS_ERROR',
});

export const GET_ORDER_ID_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/orderId/generate`,
    REQUEST: 'REQUEST_GET_ORDER_ID_DATA',
    RECEIVED: 'RECEIVED_GET_ORDER_ID_DATA',
    RECEIVED_ERROR: 'RECEIVED_GET_ORDER_ID_DATA_ERROR',
});

export const UPDATE_PRODUCTS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/updateQty`,
    REQUEST: 'REQUEST_UPDATE_PRODUCTS_DATA',
    RECEIVED: 'RECEIVED_UPDATE_PRODUCTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_UPDATE_PRODUCTS_DATA_ERROR',
});

export const GET_BRAINTREE_CLIENT_TOKEN_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/payment/braintree/token`,
    REQUEST: 'REQUEST_BRAINTREE_CLIENT_TOKEN',
    RECEIVED: 'RECEIVED_BRAINTREE_CLIENT_TOKEN',
    RECEIVED_ERROR: 'RECEIVED_BRAINTREE_CLIENT_TOKEN_ERROR',
});


export const PLACE_ORDER_DATA_URL = `${process.env.APPLICATION_BFF_URL}/rest/WG/V1/place-order`;
export const REQUEST_PLACE_DATA_ORDER = 'REQUEST_PLACE_DATA_ORDER';
export const RECEIVED_PLACE_DATA_ORDER = 'RECEIVED_PLACE_DATA_ORDER';
export const RECEIVED_PLACE_DATA_ORDER_ERROR = 'RECEIVED_PLACE_DATA_ORDER_ERROR';
