export const RECCURING_PROFILE_URL = `${process.env.APPLICATION_BFF_URL}/profiles/recurring`;
export const REQUEST_RECCURING_PROFILE_DATA = 'REQUEST_RECCURING_PROFILE_DATA';
export const RECEIVED_RECCURING_PROFILE_DATA = 'RECEIVED_RECCURING_PROFILE_DATA';
export const RECEIVED_RECCURING_PROFILE_ERROR = 'RECEIVED_RECCURING_PROFILE_ERROR';
