export const SEASONAL_URL = `${process.env.APPLICATION_BFF_URL}/subscription/seasons`;
export const REQUEST_SEASONALOPTION_DATA = 'REQUEST_SEASONALOPTION_DATA';
export const RECEIVED_SEASONALOPTION_DATA = 'RECEIVED_SEASONALOPTION_DATA';
export const RECEIVED_SEASONALOPTOIN_ERROR = 'RECEIVED_SEASONALOPTOIN_ERROR';

/* FOR CATEGORIES BASED ON SEASONAL SELECTION */
export const SEASONAL_CATEGORIES = `${process.env.APPLICATION_BFF_URL}/subscription/categories`;
export const REQUEST_SEASONALCATEGORIES = 'REQUEST_SEASONALCATEGORIES';
export const RECIVED_SEASONALCATEGORIES = 'RECIVED_SEASONALCATEGORIES';
export const RECIVED_SEASONALCATEGORIES_ERROR = 'RECIVED_SEASONALCATEGORIES_ERROR';


/* FOR SUBSCRIPTION LIST PRODUCTS */
export const SEASONAL_CATEGORIES_LIST = `${process.env.APPLICATION_BFF_URL}/subscription/products`;
export const REQUEST_SEASONALCATEGORIES_LIST = 'REQUEST_SEASONALCATEGORIES_LIST';
export const RECIVED_SEASONALCATEGORIES_LIST = 'RECIVED_SEASONALCATEGORIES_LIST';
export const RECIVED_SEASONALCATEGORIES_LIST_ERROR = 'RECIVED_SEASONALCATEGORIES_LIST_ERROR';

