
// Track Order Constants
export const TRACK_ORDER_URL = `${process.env.APPLICATION_BFF_URL}/user/trackOrder`;
export const REQUEST_TRACK_ORDER_SEARCH = 'REQUEST_TRACK_ORDER_SEARCH';
export const RECEIVED_TRACK_ORDER_SEARCH = 'RECEIVED_TRACK_ORDER_SEARCH';
export const RECEIVED_TRACK_ORDER_SEARCH_ERROR = 'RECEIVED_TRACK_ORDER_SEARCH_ERROR';
