export const VENDOR_REVIEWS_DATA_URL = `${process.env.APPLICATION_BFF_URL}/info/vendor/reviews/list`;
export const POST_VENDOR_REVIEW_URL = `${process.env.APPLICATION_BFF_URL}/info/vendor/reviews`;

export const REQUEST_VENDOR_REVIEWS_DATA = 'REQUEST_VENDOR_REVIEWS_DATA';
export const RECEIVED_VENDOR_REVIEWS_DATA = 'RECEIVED_VENDOR_REVIEWS_DATA';
export const RECEIVED_VENDOR_REVIEWS_DATA_ERROR = 'RECEIVED_VENDOR_REVIEWS_DATA_ERROR';

export const REQUEST_POST_VENDOR_REVIEWS_DATA = 'REQUEST_POST_VENDOR_REVIEWS_DATA';
export const RECEIVED_POST_VENDOR_REVIEWS_DATA = 'RECEIVED_POST_VENDOR_REVIEWS_DATA';
export const RECEIVED_POST_VENDOR_REVIEWS_DATA_ERROR = 'RECEIVED_POST_VENDOR_REVIEWS_DATA_ERROR';

export const MY_VENDOR_REVIEWS_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/reviews`,
    REQUEST: 'REQUEST_MY_VENDOR_REVIEWS',
    RECEIVED: 'RECEIVED_MY_VENDOR_REVIEWS',
    RECEIVED_ERROR: 'RECEIVED_MY_VENDOR_REVIEWS_ERROR',
});

export const PRODUCT_VENDOR_REVIEWS_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/product/vendor/reviews`,
    REQUEST: 'REQUEST_PRODUCT_VENDOR_REVIEWS',
    RECEIVED: 'RECEIVED_PRODUCT_VENDOR_REVIEWS',
    RECEIVED_ERROR: 'RECEIVED_PRODUCT_VENDOR_REVIEWS_ERROR',
});