export const VENDOR_REGISTRATION_URL = 'http://54.183.113.49:2001/admin-bff/user/login';
export const REQUEST_VENDOR_REGISTRATION_DATA = 'REQUEST_VENDOR_REGISTRATION_DATA';
export const RECEIVED_VENDOR_REGISTRATION_DATA = 'RECEIVED_VENDOR_REGISTRATION_DATA';
export const RECEIVED_VENDOR_REGISTRATION_ERROR = 'RECEIVED_VENDOR_REGISTRATION_ERROR';