export const ARTIST_VENDOR_LOGIN_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/email/`,
    REQUEST: 'REQUEST_ARTIST_VENDOR_LOGIN_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_VENDOR_LOGIN_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_VENDOR_LOGIN_CONSTANTS_ERROR',
});


export const ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/vendor/product/upload`,
    REQUEST: 'REQUEST_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_VENDOR_PRODUCT_UPLOAD_CONSTANTS_ERROR',
});

export const ARTIST_VENDOR_ORDER_MANAGEMENT_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/vendor/po/management`,
    REQUEST: 'REQUEST_ARTIST_VENDOR_ORDER_MANAGEMENT_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_VENDOR_ORDER_MANAGEMENT_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_VENDOR_ORDER_MANAGEMENT_CONSTANTS_ERROR',
});

export const ARTIST_PRODUCT_UPLOAD_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/creation`,
    REQUEST: 'REQUEST_PRODUCT_UPLOAD_CONSTANTS',
    RECEIVED: 'RECEIVED_PRODUCT_UPLOAD_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_PRODUCT_UPLOAD_CONSTANTS_ERROR',
});

export const ARTIST_PRODUCTS_LIST_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/productsByArtist`,
    REQUEST: 'REQUEST_ARTIST_PRODUCTS_LIST_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_PRODUCTS_LIST_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_PRODUCTS_LIST_CONSTANTS_ERROR',
});

export const ARTIST_PRODUCTS_UPDATE_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/update`,
    REQUEST: 'REQUEST_ARTIST_PRODUCTS_UPDATE_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_PRODUCTS_UPDATE_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_PRODUCTS_UPDATE_CONSTANTS_ERROR',
});

export const ARTIST_LOGISTIC_SETTINGS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/logisticDetails`,
    REQUEST: 'REQUEST_ARTIST_LOGISTIC_SETTINGS_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_ERROR',
});

export const ARTIST_UPDATE_LOGISTIC_SETTINGS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/logisticDetails/update`,
    REQUEST: 'REQUEST_UPDATE_ARTIST_LOGISTIC_SETTINGS_CONSTANTS',
    RECEIVED: 'RECEIVED_UPDATE_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_UPDATE_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_ERROR',
});

export const ARTIST_ADD_LOGISTIC_SETTINGS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/artist/logisticDetails/add`,
    REQUEST: 'REQUEST_ADD_ARTIST_LOGISTIC_SETTINGS_CONSTANTS',
    RECEIVED: 'RECEIVED_ADD_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ADD_ARTIST_LOGISTIC_SETTINGS_CONSTANTS_ERROR',
});

export const ARTIST_SHOW_PO_DETAILS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/vendor/itemDetails/confirm`,
    REQUEST: 'REQUEST_ARTIST_SHOW_PO_DETAILS_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_SHOW_PO_DETAILS_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_SHOW_PO_DETAILS_CONSTANTS_ERROR',
});

export const ARTIST_PO_ACTION_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/vendor/po/confirm`,
    REQUEST: 'REQUEST_ARTIST_PO_ACTION_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_PO_ACTION_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_PO_ACTION_CONSTANTS_ERROR',
});

export const ARTIST_GET_RAISE_VENDOR_INVOICE_DETAILS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/vendor/itemDetails/invoice`,
    REQUEST: 'REQUEST_GET_RAISE_VENDOR_INVOICE_DETAILS_CONSTANTS',
    RECEIVED: 'RECEIVED_GET_RAISE_VENDOR_INVOICE_DETAILS_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_GET_RAISE_VENDOR_INVOICE_DETAILS_CONSTANTS_ERROR',
});

export const ARTIST_RAISE_INVOICE_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/vendor/raiseInvoice`,
    REQUEST: 'REQUEST_RAISE_INVOICE_CONSTANTS',
    RECEIVED: 'RECEIVED_RAISE_INVOICE_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_RAISE_INVOICE_CONSTANTS_ERROR',
});

export const ARTIST_LOGIN_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/vendor/login`,
    REQUEST: 'REQUEST_ARTIST_LOGIN_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_LOGIN_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_LOGIN_CONSTANTS_ERROR',
});

export const ARTIST_LOGOUT_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/vendor/logout`,
    REQUEST: 'REQUEST_ARTIST_LOGOUT_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_LOGOUT_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_LOGOUT_CONSTANTS_ERROR',
});

export const ARTIST_PRODUCT_REQUIREMENTS_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/product/creation/requirements`,
    REQUEST: 'REQUEST_ARTIST_PRODUCT_REQUIREMENTS_CONSTANTS',
    RECEIVED: 'RECEIVED_ARTIST_PRODUCT_REQUIREMENTS_CONSTANTS_DATA',
    RECEIVED_ERROR: 'RECEIVED_ARTIST_PRODUCT_REQUIREMENTS_CONSTANTS_ERROR',
});
