export const WISHLIST_DATA_URL = `${process.env.APPLICATION_BFF_URL}/info/wishlist/list`;
export const REQUEST_WISHLIST_INFO = 'REQUEST_WISHLIST_INFO';
export const RECEIVE_WISHLIST_INFO = 'RECEIVE_WISHLIST_INFO';
export const RECEIVED_WISHLIST_INFO_ERROR = 'RECEIVED_WISHLIST_INFO_ERROR';


export const WISHLIST_REMOVE_URL = `${process.env.APPLICATION_BFF_URL}/info/wishlist`;
export const REQUEST_REMOVE_FROM_WISHLIST = 'REQUEST_REMOVE_FROM_WISHLIST';
export const RECEIVE_UPDATED_WISHLIST_INFO = 'RECEIVE_UPDATED_WISHLIST_INFO';
export const RECEIVED_UPDATED_WISHLIST_INFO_ERROR = 'RECEIVED_UPDATED_WISHLIST_INFO_ERROR';

export const ADD_TO_WISHLIST_URL_CONSTANTS = ({
    URL: `${process.env.APPLICATION_BFF_URL}/info/wishlist`,
    REQUEST: 'REQUEST_SUBMIT_ADD_TO_WISHLIST',
    RECEIVED: 'RECEIVED_SUBMIT_ADD_TO_WISHLIST',
    RECEIVED_ERROR: 'RECEIVED_SUBMIT_ADD_TO_WISHLIST_ERROR',
});

export const CLEAR_WISHLIST_DATA = 'CLEAR_WISHLIST_DATA';
